// This file is intentionally inert.
//
// /robots.txt is now generated by the nuxt-robots module (configured in
// nuxt.config.ts). File kept (instead of deleted) because the build
// environment can't remove files. Nitro only registers a route when there
// is a default export with an event handler — exporting nothing keeps
// this path out of the routing table so the module can own it.
export {}
