// This file is intentionally inert.
//
// /sitemap.xml is now generated by the @nuxtjs/sitemap module (configured
// in nuxt.config.ts), which has deeper i18n + module integration than the
// hand-rolled handler that used to live here.
//
// File kept (instead of deleted) because the build environment can't
// remove files. Nitro only registers a route when there is a default
// export with an event handler — exporting nothing keeps this route
// out of the routing table so the module can own it.
export {}
